[book]
title    = "@title@"
language = "en"
src      = "."

[build]
build-dir      = "book"
create-missing = false

[output.html]
default-theme          = "navy"
preferred-dark-theme   = "navy"
no-section-label       = true
git-repository-url     = "https://github.com/asynthe/flakes"

[output.html.search]
enable            = true
limit-results     = 20
use-boolean-and   = true

[output.html.fold]
enable = true
level  = 1
